### ISSUE TITLE
Boolean type parses values 0 and 1 backwards

### ISSUE THREAD

**Issue by dsagal** [okfn/messytables#154] opened 2016-07-05 20:49 UTC
This code https://github.com/okfn/messytables/blob/master/messytables/types.py#L117 considers "0" to be True, and "1" to be False. That seems the opposite of what it should do.

**Comment by StevenMaude** [comment] 2016-10-04 19:37
Thanks for reporting. This is a duplicate of #146; closing.

**Closed by StevenMaude** 2016-10-04 19:37 UTC
